version: '3.9'
services:
  app:
    build:
      context: .
      network: host
    container_name: test5-dev
    working_dir: /workspace
    command: tail -f /dev/null
    volumes:
      - ./:/workspace
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
